### ISSUE TITLE
Error in Update_prediction()

### ISSUE THREAD

**Issue by LuisACubillos** [James-Thorson/FishLife#11]
I have this piece of code:

Predict=Plot_taxa(Search_species(Genus="Brama",Species="australis")$match_taxonomy,mfrow=c(2,2))
Obs_Loo <- c(56.9,59.55,58.95,60.9)
Obs_K <- c(0.18,0.19,0.28,0.13)

Ynew_ij <- matrix(c("Loo"=log(Obs_Loo),"K"=log(Obs_K),"Winfinity"=rep(NA,4),"tmax"=rep(NA,4),"tm"=rep(NA,4),"M"=rep(NA,4),"Lm"=rep(NA,4),"Temperature"=rep(NA,4)), nrow=4)
library(TMB)
Update = Update_prediction(Taxon=Search_species(Genus="Brama",Species="australis",add_ancestors=FALSE)$match_taxonomy, Ynew_ij=Ynew_ij)
Update$updateMean_j

Then the following Error was obtained in the console :

13 warnings generated.
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o Update_v1_0_0.so Update_v1_0_0.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
Error in sqrt(unlist(tmp)) : 
  non-numeric argument to mathematical function
In addition: Warning message:
'TMBhelper::Optimize' is deprecated.
Use 'fit_tmb' instead.
See help("Deprecated")

**Comment by James-Thorson** [comment]
Do you get this error with the pre-packaged example in the vignette?

**Comment by LuisACubillos** [comment]
I ran an updating function for Cortez rockfish (in the pre-packaged example in the vignette), and the same error was displayed in the console ( the same occurred for R v 1.6).

**Comment by LuisACubillos** [comment]
Yes, I do. same error with the pre-packaged example.

Prof. Dr. Luis Cubillos
Profesor Asociado
Departamento Oceanografía
Facultad de Ciencias Naturales y Oceanográficas
Tel.: 56-41-2 207 233
Email: lucubillos@udec.cl
Scholar Google Citations
<http://scholar.google.es/citations?hl=es&user=pLQd6tQAAAAJ>
ResearchGate <https://www.researchgate.net/profile/Luis_Cubillos>

**Comment by James-Thorson** [comment]
Then its probably a problem with your installation of TMB, please follow the steps here: https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/Steps-to-install-TMB and report back when you can replicate the TMB run in that script.

**Comment by LuisACubillos** [comment]
Dear Jim,
The installation of TMB was fine. I followed your instructions and obtained
the following output:
> Obj$fn( Obj$par )
Optimizing tape... Done
iter: 1  value: 330.6136 mgc: 2.148318 ustep: 1
iter: 2  mgc: 8.743006e-16
[1] 313.4137
attr(,"logarithm")
[1] TRUE

Nevertheless, when I tried to obtain an update with new parameters, the
early error remain in the FishLife package; i.e.,

Error in sqrt(unlist(tmp)) :
  non-numeric argument to mathematical function
In addition: Warning message:
'TMBhelper::Optimize' is deprecated.
Use 'fit_tmb' instead.
See help("Deprecated")

I have used 'TMBhelper::fit_tmb' instead of 'Optimize' in another example
and that is OK. I think the problem is with a list in tmp.


Prof. Dr. Luis Cubillos
Profesor Asociado
Departamento Oceanografía
Facultad de Ciencias Naturales y Oceanográficas
Tel.: 56-41-2 207 233
Email: lucubillos@udec.cl
Scholar Google Citations
<http://scholar.google.es/citations?hl=es&user=pLQd6tQAAAAJ>
ResearchGate <https://www.researchgate.net/profile/Luis_Cubillos>

**Comment by James-Thorson-NOAA** [comment]
Thanks for double-checking your installation, and sorry for my very slow response. It took a bit of time, but I tracked the issue down to an issue in TMB, where `getJointPrecision=TRUE` throws an error when `getReportCovariance=FALSE`.  Anyway, it is now fixed in the development branch, feel free to try again and respond if that didn't solve it.
